/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as NewsNewsIdRouteImport } from './routes/news/$newsId'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard/payments'
import { Route as DashboardLoansRouteImport } from './routes/dashboard/loans'
import { Route as DashboardDepositsRouteImport } from './routes/dashboard/deposits'
import { Route as DashboardCardsRouteImport } from './routes/dashboard/cards'
import { Route as DashboardApplicationsRouteImport } from './routes/dashboard/applications'
import { Route as DashboardAccountsRouteImport } from './routes/dashboard/accounts'
import { Route as DashboardAccountsAccountIdRouteImport } from './routes/dashboard/accounts/$accountId'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsNewsIdRoute = NewsNewsIdRouteImport.update({
  id: '/news/$newsId',
  path: '/news/$newsId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLoansRoute = DashboardLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDepositsRoute = DashboardDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCardsRoute = DashboardCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardApplicationsRoute = DashboardApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountsRoute = DashboardAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountsAccountIdRoute =
  DashboardAccountsAccountIdRouteImport.update({
    id: '/$accountId',
    path: '/$accountId',
    getParentRoute: () => DashboardAccountsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard/accounts': typeof DashboardAccountsRouteWithChildren
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/cards': typeof DashboardCardsRoute
  '/dashboard/deposits': typeof DashboardDepositsRoute
  '/dashboard/loans': typeof DashboardLoansRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/news/': typeof NewsIndexRoute
  '/dashboard/accounts/$accountId': typeof DashboardAccountsAccountIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard/accounts': typeof DashboardAccountsRouteWithChildren
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/cards': typeof DashboardCardsRoute
  '/dashboard/deposits': typeof DashboardDepositsRoute
  '/dashboard/loans': typeof DashboardLoansRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard': typeof DashboardIndexRoute
  '/news': typeof NewsIndexRoute
  '/dashboard/accounts/$accountId': typeof DashboardAccountsAccountIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard/accounts': typeof DashboardAccountsRouteWithChildren
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/cards': typeof DashboardCardsRoute
  '/dashboard/deposits': typeof DashboardDepositsRoute
  '/dashboard/loans': typeof DashboardLoansRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/news/': typeof NewsIndexRoute
  '/dashboard/accounts/$accountId': typeof DashboardAccountsAccountIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/contact'
    | '/dashboard/accounts'
    | '/dashboard/applications'
    | '/dashboard/cards'
    | '/dashboard/deposits'
    | '/dashboard/loans'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/news/$newsId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/'
    | '/news/'
    | '/dashboard/accounts/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/dashboard/accounts'
    | '/dashboard/applications'
    | '/dashboard/cards'
    | '/dashboard/deposits'
    | '/dashboard/loans'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/news/$newsId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard'
    | '/news'
    | '/dashboard/accounts/$accountId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/contact'
    | '/dashboard/accounts'
    | '/dashboard/applications'
    | '/dashboard/cards'
    | '/dashboard/deposits'
    | '/dashboard/loans'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/news/$newsId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/'
    | '/news/'
    | '/dashboard/accounts/$accountId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ContactRoute: typeof ContactRoute
  NewsNewsIdRoute: typeof NewsNewsIdRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$newsId': {
      id: '/news/$newsId'
      path: '/news/$newsId'
      fullPath: '/news/$newsId'
      preLoaderRoute: typeof NewsNewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/loans': {
      id: '/dashboard/loans'
      path: '/loans'
      fullPath: '/dashboard/loans'
      preLoaderRoute: typeof DashboardLoansRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/deposits': {
      id: '/dashboard/deposits'
      path: '/deposits'
      fullPath: '/dashboard/deposits'
      preLoaderRoute: typeof DashboardDepositsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/cards': {
      id: '/dashboard/cards'
      path: '/cards'
      fullPath: '/dashboard/cards'
      preLoaderRoute: typeof DashboardCardsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/applications': {
      id: '/dashboard/applications'
      path: '/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof DashboardApplicationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accounts': {
      id: '/dashboard/accounts'
      path: '/accounts'
      fullPath: '/dashboard/accounts'
      preLoaderRoute: typeof DashboardAccountsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accounts/$accountId': {
      id: '/dashboard/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/dashboard/accounts/$accountId'
      preLoaderRoute: typeof DashboardAccountsAccountIdRouteImport
      parentRoute: typeof DashboardAccountsRoute
    }
  }
}

interface DashboardAccountsRouteChildren {
  DashboardAccountsAccountIdRoute: typeof DashboardAccountsAccountIdRoute
}

const DashboardAccountsRouteChildren: DashboardAccountsRouteChildren = {
  DashboardAccountsAccountIdRoute: DashboardAccountsAccountIdRoute,
}

const DashboardAccountsRouteWithChildren =
  DashboardAccountsRoute._addFileChildren(DashboardAccountsRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAccountsRoute: typeof DashboardAccountsRouteWithChildren
  DashboardApplicationsRoute: typeof DashboardApplicationsRoute
  DashboardCardsRoute: typeof DashboardCardsRoute
  DashboardDepositsRoute: typeof DashboardDepositsRoute
  DashboardLoansRoute: typeof DashboardLoansRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAccountsRoute: DashboardAccountsRouteWithChildren,
  DashboardApplicationsRoute: DashboardApplicationsRoute,
  DashboardCardsRoute: DashboardCardsRoute,
  DashboardDepositsRoute: DashboardDepositsRoute,
  DashboardLoansRoute: DashboardLoansRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ContactRoute: ContactRoute,
  NewsNewsIdRoute: NewsNewsIdRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
