/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as NewsNewsIdRouteImport } from './routes/news/$newsId'
import { Route as LocaleContactRouteImport } from './routes/$locale/contact'
import { Route as LocaleDashboardRouteRouteImport } from './routes/$locale/dashboard/route'
import { Route as LocaleNewsIndexRouteImport } from './routes/$locale/news/index'
import { Route as LocaleDashboardIndexRouteImport } from './routes/$locale/dashboard/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LocaleSignUpSplatRouteImport } from './routes/$locale/sign-up.$'
import { Route as LocaleSignInSplatRouteImport } from './routes/$locale/sign-in.$'
import { Route as LocaleNewsNewsIdRouteImport } from './routes/$locale/news/$newsId'
import { Route as LocaleDashboardSettingsRouteImport } from './routes/$locale/dashboard/settings'
import { Route as LocaleDashboardPaymentsRouteImport } from './routes/$locale/dashboard/payments'
import { Route as LocaleDashboardLoansRouteImport } from './routes/$locale/dashboard/loans'
import { Route as LocaleDashboardDepositsRouteImport } from './routes/$locale/dashboard/deposits'
import { Route as LocaleDashboardCardsRouteImport } from './routes/$locale/dashboard/cards'
import { Route as LocaleDashboardApplicationsRouteImport } from './routes/$locale/dashboard/applications'
import { Route as LocaleDashboardAccountsRouteImport } from './routes/$locale/dashboard/accounts'
import { Route as LocaleDashboardAccountsAccountIdRouteImport } from './routes/$locale/dashboard/accounts/$accountId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsNewsIdRoute = NewsNewsIdRouteImport.update({
  id: '/news/$newsId',
  path: '/news/$newsId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleDashboardRouteRoute = LocaleDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleNewsIndexRoute = LocaleNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleDashboardIndexRoute = LocaleDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleDashboardRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSignUpSplatRoute = LocaleSignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleSignInSplatRoute = LocaleSignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleNewsNewsIdRoute = LocaleNewsNewsIdRouteImport.update({
  id: '/news/$newsId',
  path: '/news/$newsId',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleDashboardSettingsRoute = LocaleDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LocaleDashboardRouteRoute,
} as any)
const LocaleDashboardPaymentsRoute = LocaleDashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => LocaleDashboardRouteRoute,
} as any)
const LocaleDashboardLoansRoute = LocaleDashboardLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => LocaleDashboardRouteRoute,
} as any)
const LocaleDashboardDepositsRoute = LocaleDashboardDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => LocaleDashboardRouteRoute,
} as any)
const LocaleDashboardCardsRoute = LocaleDashboardCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => LocaleDashboardRouteRoute,
} as any)
const LocaleDashboardApplicationsRoute =
  LocaleDashboardApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => LocaleDashboardRouteRoute,
  } as any)
const LocaleDashboardAccountsRoute = LocaleDashboardAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => LocaleDashboardRouteRoute,
} as any)
const LocaleDashboardAccountsAccountIdRoute =
  LocaleDashboardAccountsAccountIdRouteImport.update({
    id: '/$accountId',
    path: '/$accountId',
    getParentRoute: () => LocaleDashboardAccountsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/$locale/dashboard': typeof LocaleDashboardRouteRouteWithChildren
  '/$locale/contact': typeof LocaleContactRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/$locale/': typeof LocaleIndexRoute
  '/news/': typeof NewsIndexRoute
  '/$locale/dashboard/accounts': typeof LocaleDashboardAccountsRouteWithChildren
  '/$locale/dashboard/applications': typeof LocaleDashboardApplicationsRoute
  '/$locale/dashboard/cards': typeof LocaleDashboardCardsRoute
  '/$locale/dashboard/deposits': typeof LocaleDashboardDepositsRoute
  '/$locale/dashboard/loans': typeof LocaleDashboardLoansRoute
  '/$locale/dashboard/payments': typeof LocaleDashboardPaymentsRoute
  '/$locale/dashboard/settings': typeof LocaleDashboardSettingsRoute
  '/$locale/news/$newsId': typeof LocaleNewsNewsIdRoute
  '/$locale/sign-in/$': typeof LocaleSignInSplatRoute
  '/$locale/sign-up/$': typeof LocaleSignUpSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$locale/dashboard/': typeof LocaleDashboardIndexRoute
  '/$locale/news/': typeof LocaleNewsIndexRoute
  '/$locale/dashboard/accounts/$accountId': typeof LocaleDashboardAccountsAccountIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/$locale': typeof LocaleIndexRoute
  '/news': typeof NewsIndexRoute
  '/$locale/dashboard/accounts': typeof LocaleDashboardAccountsRouteWithChildren
  '/$locale/dashboard/applications': typeof LocaleDashboardApplicationsRoute
  '/$locale/dashboard/cards': typeof LocaleDashboardCardsRoute
  '/$locale/dashboard/deposits': typeof LocaleDashboardDepositsRoute
  '/$locale/dashboard/loans': typeof LocaleDashboardLoansRoute
  '/$locale/dashboard/payments': typeof LocaleDashboardPaymentsRoute
  '/$locale/dashboard/settings': typeof LocaleDashboardSettingsRoute
  '/$locale/news/$newsId': typeof LocaleNewsNewsIdRoute
  '/$locale/sign-in/$': typeof LocaleSignInSplatRoute
  '/$locale/sign-up/$': typeof LocaleSignUpSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$locale/dashboard': typeof LocaleDashboardIndexRoute
  '/$locale/news': typeof LocaleNewsIndexRoute
  '/$locale/dashboard/accounts/$accountId': typeof LocaleDashboardAccountsAccountIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/$locale/dashboard': typeof LocaleDashboardRouteRouteWithChildren
  '/$locale/contact': typeof LocaleContactRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/$locale/': typeof LocaleIndexRoute
  '/news/': typeof NewsIndexRoute
  '/$locale/dashboard/accounts': typeof LocaleDashboardAccountsRouteWithChildren
  '/$locale/dashboard/applications': typeof LocaleDashboardApplicationsRoute
  '/$locale/dashboard/cards': typeof LocaleDashboardCardsRoute
  '/$locale/dashboard/deposits': typeof LocaleDashboardDepositsRoute
  '/$locale/dashboard/loans': typeof LocaleDashboardLoansRoute
  '/$locale/dashboard/payments': typeof LocaleDashboardPaymentsRoute
  '/$locale/dashboard/settings': typeof LocaleDashboardSettingsRoute
  '/$locale/news/$newsId': typeof LocaleNewsNewsIdRoute
  '/$locale/sign-in/$': typeof LocaleSignInSplatRoute
  '/$locale/sign-up/$': typeof LocaleSignUpSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$locale/dashboard/': typeof LocaleDashboardIndexRoute
  '/$locale/news/': typeof LocaleNewsIndexRoute
  '/$locale/dashboard/accounts/$accountId': typeof LocaleDashboardAccountsAccountIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/contact'
    | '/dashboard'
    | '/$locale/dashboard'
    | '/$locale/contact'
    | '/news/$newsId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$locale/'
    | '/news/'
    | '/$locale/dashboard/accounts'
    | '/$locale/dashboard/applications'
    | '/$locale/dashboard/cards'
    | '/$locale/dashboard/deposits'
    | '/$locale/dashboard/loans'
    | '/$locale/dashboard/payments'
    | '/$locale/dashboard/settings'
    | '/$locale/news/$newsId'
    | '/$locale/sign-in/$'
    | '/$locale/sign-up/$'
    | '/api/auth/$'
    | '/$locale/dashboard/'
    | '/$locale/news/'
    | '/$locale/dashboard/accounts/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/$locale/contact'
    | '/news/$newsId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$locale'
    | '/news'
    | '/$locale/dashboard/accounts'
    | '/$locale/dashboard/applications'
    | '/$locale/dashboard/cards'
    | '/$locale/dashboard/deposits'
    | '/$locale/dashboard/loans'
    | '/$locale/dashboard/payments'
    | '/$locale/dashboard/settings'
    | '/$locale/news/$newsId'
    | '/$locale/sign-in/$'
    | '/$locale/sign-up/$'
    | '/api/auth/$'
    | '/$locale/dashboard'
    | '/$locale/news'
    | '/$locale/dashboard/accounts/$accountId'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/contact'
    | '/dashboard'
    | '/$locale/dashboard'
    | '/$locale/contact'
    | '/news/$newsId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$locale/'
    | '/news/'
    | '/$locale/dashboard/accounts'
    | '/$locale/dashboard/applications'
    | '/$locale/dashboard/cards'
    | '/$locale/dashboard/deposits'
    | '/$locale/dashboard/loans'
    | '/$locale/dashboard/payments'
    | '/$locale/dashboard/settings'
    | '/$locale/news/$newsId'
    | '/$locale/sign-in/$'
    | '/$locale/sign-up/$'
    | '/api/auth/$'
    | '/$locale/dashboard/'
    | '/$locale/news/'
    | '/$locale/dashboard/accounts/$accountId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  NewsNewsIdRoute: typeof NewsNewsIdRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$newsId': {
      id: '/news/$newsId'
      path: '/news/$newsId'
      fullPath: '/news/$newsId'
      preLoaderRoute: typeof NewsNewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/dashboard': {
      id: '/$locale/dashboard'
      path: '/dashboard'
      fullPath: '/$locale/dashboard'
      preLoaderRoute: typeof LocaleDashboardRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/news/': {
      id: '/$locale/news/'
      path: '/news'
      fullPath: '/$locale/news/'
      preLoaderRoute: typeof LocaleNewsIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/dashboard/': {
      id: '/$locale/dashboard/'
      path: '/'
      fullPath: '/$locale/dashboard/'
      preLoaderRoute: typeof LocaleDashboardIndexRouteImport
      parentRoute: typeof LocaleDashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/sign-up/$': {
      id: '/$locale/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/$locale/sign-up/$'
      preLoaderRoute: typeof LocaleSignUpSplatRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/sign-in/$': {
      id: '/$locale/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/$locale/sign-in/$'
      preLoaderRoute: typeof LocaleSignInSplatRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/news/$newsId': {
      id: '/$locale/news/$newsId'
      path: '/news/$newsId'
      fullPath: '/$locale/news/$newsId'
      preLoaderRoute: typeof LocaleNewsNewsIdRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/dashboard/settings': {
      id: '/$locale/dashboard/settings'
      path: '/settings'
      fullPath: '/$locale/dashboard/settings'
      preLoaderRoute: typeof LocaleDashboardSettingsRouteImport
      parentRoute: typeof LocaleDashboardRouteRoute
    }
    '/$locale/dashboard/payments': {
      id: '/$locale/dashboard/payments'
      path: '/payments'
      fullPath: '/$locale/dashboard/payments'
      preLoaderRoute: typeof LocaleDashboardPaymentsRouteImport
      parentRoute: typeof LocaleDashboardRouteRoute
    }
    '/$locale/dashboard/loans': {
      id: '/$locale/dashboard/loans'
      path: '/loans'
      fullPath: '/$locale/dashboard/loans'
      preLoaderRoute: typeof LocaleDashboardLoansRouteImport
      parentRoute: typeof LocaleDashboardRouteRoute
    }
    '/$locale/dashboard/deposits': {
      id: '/$locale/dashboard/deposits'
      path: '/deposits'
      fullPath: '/$locale/dashboard/deposits'
      preLoaderRoute: typeof LocaleDashboardDepositsRouteImport
      parentRoute: typeof LocaleDashboardRouteRoute
    }
    '/$locale/dashboard/cards': {
      id: '/$locale/dashboard/cards'
      path: '/cards'
      fullPath: '/$locale/dashboard/cards'
      preLoaderRoute: typeof LocaleDashboardCardsRouteImport
      parentRoute: typeof LocaleDashboardRouteRoute
    }
    '/$locale/dashboard/applications': {
      id: '/$locale/dashboard/applications'
      path: '/applications'
      fullPath: '/$locale/dashboard/applications'
      preLoaderRoute: typeof LocaleDashboardApplicationsRouteImport
      parentRoute: typeof LocaleDashboardRouteRoute
    }
    '/$locale/dashboard/accounts': {
      id: '/$locale/dashboard/accounts'
      path: '/accounts'
      fullPath: '/$locale/dashboard/accounts'
      preLoaderRoute: typeof LocaleDashboardAccountsRouteImport
      parentRoute: typeof LocaleDashboardRouteRoute
    }
    '/$locale/dashboard/accounts/$accountId': {
      id: '/$locale/dashboard/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/$locale/dashboard/accounts/$accountId'
      preLoaderRoute: typeof LocaleDashboardAccountsAccountIdRouteImport
      parentRoute: typeof LocaleDashboardAccountsRoute
    }
  }
}

interface LocaleDashboardAccountsRouteChildren {
  LocaleDashboardAccountsAccountIdRoute: typeof LocaleDashboardAccountsAccountIdRoute
}

const LocaleDashboardAccountsRouteChildren: LocaleDashboardAccountsRouteChildren =
  {
    LocaleDashboardAccountsAccountIdRoute:
      LocaleDashboardAccountsAccountIdRoute,
  }

const LocaleDashboardAccountsRouteWithChildren =
  LocaleDashboardAccountsRoute._addFileChildren(
    LocaleDashboardAccountsRouteChildren,
  )

interface LocaleDashboardRouteRouteChildren {
  LocaleDashboardAccountsRoute: typeof LocaleDashboardAccountsRouteWithChildren
  LocaleDashboardApplicationsRoute: typeof LocaleDashboardApplicationsRoute
  LocaleDashboardCardsRoute: typeof LocaleDashboardCardsRoute
  LocaleDashboardDepositsRoute: typeof LocaleDashboardDepositsRoute
  LocaleDashboardLoansRoute: typeof LocaleDashboardLoansRoute
  LocaleDashboardPaymentsRoute: typeof LocaleDashboardPaymentsRoute
  LocaleDashboardSettingsRoute: typeof LocaleDashboardSettingsRoute
  LocaleDashboardIndexRoute: typeof LocaleDashboardIndexRoute
}

const LocaleDashboardRouteRouteChildren: LocaleDashboardRouteRouteChildren = {
  LocaleDashboardAccountsRoute: LocaleDashboardAccountsRouteWithChildren,
  LocaleDashboardApplicationsRoute: LocaleDashboardApplicationsRoute,
  LocaleDashboardCardsRoute: LocaleDashboardCardsRoute,
  LocaleDashboardDepositsRoute: LocaleDashboardDepositsRoute,
  LocaleDashboardLoansRoute: LocaleDashboardLoansRoute,
  LocaleDashboardPaymentsRoute: LocaleDashboardPaymentsRoute,
  LocaleDashboardSettingsRoute: LocaleDashboardSettingsRoute,
  LocaleDashboardIndexRoute: LocaleDashboardIndexRoute,
}

const LocaleDashboardRouteRouteWithChildren =
  LocaleDashboardRouteRoute._addFileChildren(LocaleDashboardRouteRouteChildren)

interface LocaleRouteRouteChildren {
  LocaleDashboardRouteRoute: typeof LocaleDashboardRouteRouteWithChildren
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleNewsNewsIdRoute: typeof LocaleNewsNewsIdRoute
  LocaleSignInSplatRoute: typeof LocaleSignInSplatRoute
  LocaleSignUpSplatRoute: typeof LocaleSignUpSplatRoute
  LocaleNewsIndexRoute: typeof LocaleNewsIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleDashboardRouteRoute: LocaleDashboardRouteRouteWithChildren,
  LocaleContactRoute: LocaleContactRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleNewsNewsIdRoute: LocaleNewsNewsIdRoute,
  LocaleSignInSplatRoute: LocaleSignInSplatRoute,
  LocaleSignUpSplatRoute: LocaleSignUpSplatRoute,
  LocaleNewsIndexRoute: LocaleNewsIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  NewsNewsIdRoute: NewsNewsIdRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  NewsIndexRoute: NewsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
